
## TO RUN: `bundle exec jekyll serve`
# --- General options --- #


title: Evan Odell
description: Various Things

# --- Navigation bar options --- #
# List of links in the navigation bar
navbar-links:
  Home: "http://evanodell.com"
  About: "about"
  CV: "cv"
#  - Publications: "http://evanodell.com/cv/#publications"
  Projects: "projects"
#  Shiny Apps: "shiny"
#  Datasets: "datasets"
  Blog: "blog"

# Image to show in the navigation bar - image must be a square (width = height)
#avatar: "/img/EvanOdell.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: "/img/EvanOdell.jpg"

# --- Footer options --- #
author:
  name: Evan Odell
  email: "evanodell91@gmail.com"
  github: EvanOdell
  twitter: evanodell
  linkedin: evanodell
  orcid: 0000-0003-1845-808X

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  stackoverflow: false
  orcid: true

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
  reddit: true

# footer link
url-pretty: "evanodell.com"

# scholar settings

scholar:
  style: apa
  order: descending
  bibtex_filters:
  - latex
  #- markdown



# --- Misc --- #
disqus: "evanodell"
creative-commons: true
google_analytics: "UA-90706059-1"

# Google Tag Manager ID
#gtm: ""

# Excerpt Word Length
excerpt_length: 50

# Character used to separate site title and description in HTML document title
title-separator: "-"

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true # allows for the post to be a post
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      show-title: true # shows the title of the post
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      show-title: true # shows the title of the page
  -
    scope:
      path: ""
      type: "shiny-post"
    values:
      layout: "shiny-post"
      comments: true #
      is_shiny-post: true #
      social-share: true #
      show-title: false #

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - rakefile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll/scholar

whitelist:
  - jekyll-redirect-from

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

# Extensive modifications made by Evan Odell
