baseurl = "/"
#DefaultContentLanguage = "en"
title = "Evan Odell"
theme = "beautifulhugo"
metaDataFormat = "yaml"
disqusShortname = "evanodell"
google_analytics = ""

[Params]
  subtitle = ""
  logo = "img/EvanOdell.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-01"
  commit = false
  rss = false
  comments = true
  readingTime = false
  useHLJS = true
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "far"
  UseChroma = false
  summaryLength = 50

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.bib$"]
footnotereturnlinkcontents = "<sup>^</sup>"


# Set to true to disable code folding
#disable_codefolding = false
# Set to "hide" or "show" all codes by default
#codefolding_show = "hide"


fractions = false

[author]
  name = "Evan Odell"
  website = "https://evanodell.com"
  email = "evan@evanodell.com"
  github = "evanodell"
  #gitlab = "username"
  twitter = "evanodell"
  linkedin = "evanodell"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
    
    
[[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 3
    
    
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 4

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 5
    
    
[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
    projects = "/:slug/"