# COMMENT: These are two rules with all the fields expanded
# COMMENT: This is an expanded syntax for rules that won't fit in one line
[[redirects]]
  from = "/blog/2018/02/28/golf-and-train-stations/maps/golf-map.html"
  to = "/maps/golf-map.html"
  status = 301
  force = false
[[redirects]]
  from = "/cv"
  to = "/evanodell.github.io/cv"
  status = 301
  force = false

[context.production.environment]
  HUGO_VERSION = "0.65.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.65.3"
