---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  # md_document:
  #   variant: gfm
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: a4paper, margin=2cm
author: Evan Odell
#address: "Flat 7 Halkett House Waterloo Gardens, London, UK, E2 9HU"
#phone: +44 7478 304 728
website: evanodell.com
email: "evan@evanodell.com"
twitter: evanodell
github: evanodell
linkedin: evanodell
date: "`r format(Sys.time(), '%B %Y')`"
title: "CV"
#orcid:  xxxxx
fontawesome: yes
updated: false
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue(munsell)
---
<!-- *CV template adapted from* [S. Miller](https://github.com/svmiller/svm-r-markdown-templates) -->
<!-- Please edit the .RMD file, and not the .MD!!! -->

# Education  
<!-- Oxford -->
**MSc in Comparative Social Policy**  
University of Oxford, Oxford, UK \hfill 2014 -- 2015

<!-- UBC -->
**Visiting Student**  
University of British Columbia, Vancouver, Canada \hfill 2013 -- 2014

<!-- Laurentian -->
**BA (Honours) in Political Science**  
Laurentian University, Sudbury/Barrie, Canada \hfill 2009 -- 2014

# Skill Highlights 

- Quantitative research, primarily with R

- Qualitative research and analysis

- \LaTeX\ 

- Data visualisation, both static and interactive

- Broadcast and print media interviews

# Professional Experience
## Researcher  
_Disability Rights UK_ \hfill June 2016 - present  

- Responsible for policy work on employment issues, and research on any additional issues prioritised by Disability Rights UK. This included writing briefing papers for internal and external use, responding to consultations, monitoring government policy developments and work from other sources.  

- Produced statistical briefing papers and presentations based on my analysis of a range of sources, using national and international surveys and administrative data.

- Primary researcher and annual report author evaluating "Bridge to Work", a City Bridge Trust-funded programme of training, work experience and employer engagement to increase young disabled people's employment. The evaluation focuses on changes in employer attitudes and overall impact on participant employment.  

- Lead researcher and programme manager for project on £40,000 research project on young people's attitudes to disability, conducted with the Centre for Education and Youth. I recruited and managed a steering group of young disabled people to determine the focus of the project and provide feedback on our research questions and findings.  

- Undertook small, mixed-method research projects on healthcare inequalities, the effectiveness of peer support interventions, attitudes to inclusive education, and the potential impact of different disability benefit reforms. 

- Delivering training and presenting research work to external audiences.  

## Instructor in Health Studies  
_Queen's University, Bader International Study Centre_ \hfill May 2019  

- Designed and taught "Disability Studies: Issues, Research and Policy", a final-year undergraduate course with a particular focus on employment issues and comparative analysis of welfare states.

## Data Analyst (Freelance) 
_London Business School_ \hfill June 2018 -- October 2018  

- Analysed speeches in Hansard to identify differences in the topics and language style between male and female Labour MPs, and between female Labour MPs selected through open or all-women shortlists.  

- Designed a methodology using structured topic models, and wrote out my methods and produced data visuals and statistical tables for use in a future paper on the subject.

## Performance and Impact Officer  
_The Future Leaders Trust_ \hfill October 2015 -- June 2016  

- Conducted primary and secondary analysis of school performance data, disseminated results internally through presentations and internal reports, and externally through press releases.

- Co-authored the first original research report published by the Trust, responsible for data collection and methodology, and contributed to the writing of the report.  

## Research and Teaching Assistant  
_Laurentian University_  \hfill October 2012 -- April 2013  

- Responsible for locating, summarising and organising research material for two professors in Political Science and English Literature, respectively.  

# Projects

## Bridge to Work Programme Evaluation  
Primary researcher and annual report author \hfill January 2018 -- December 2023  
Funder: City Bridge Trust \hfill £100,000  

## Disabled People Accessing Community-Based Activities  
Lead researcher and report author \hfill February 2020 -- March 2020  
Funder: NHS Personalised Care Group \hfill £10,000  

## Access to Advice Services in London  
Data analyst and report author \hfill December 2019 -- February 2020  
Funder: Nuffield Foundation \hfill £5,000  

## Inclusive Education and Co-Production  
Principle investigator \hfill December 2018 -- June 2019  
Funder: European Association of Service Providers for Persons with Disabilities \hfill €4,000  

## Young People's Attitudes to Disability  
Lead researcher and report author \hfill April 2018 -- August 2019  
Funder: Disability Research on Independent Living & Learning (DRILL) \hfill £40,000  

# Professional Memberships
- Fellow of the Royal Statistical Society
- Fellow of the Royal Society for the encouragement of Arts, Manufactures and Commerce 

# Publications 

\raggedright
## Peer Reviewed Articles  
**Odell, E.** (2017). Lonely schools: The relationship between geographic isolation and academic attainment. _Educational Research_, 59(3), 257–272. DOI: [10.1080/00131881.2017.1339285](https://doi.org/10.1080/00131881.2017.1339285)  

## Reports and Preprints  
Hale, C., Benstead, S., Lyus, J., **Odell, E.**, & Ruddock, A. (2020). Energy Impairment and Disability Inclusion. The Centre for Welfare Reform. [centreforwelfarereform.org/uploads/attachment/681/energy-impairment-and-disability-inclusion.pdf](https://www.centreforwelfarereform.org/uploads/attachment/681/energy-impairment-and-disability-inclusion.pdf)  
**Odell, E.** (2020). Getting it right the ﬁrst time: Financial penalties to improve disability beneﬁt assessments. _LawArXiv_. DOI: [10.31228/osf.io/jksyp  ](https://doi.org/10.31228/osf.io/jksyp)  
**Odell, E.** (2019). Special or Unique: Young People’s Attitudes to Disability. Disability Rights UK. [drilluk.org.uk/wp-content/uploads/2019/08/DR-UK-Special-or-Unique-August-2019.pdf](http://www.drilluk.org.uk/wp-content/uploads/2019/08/DR-UK-Special-or-Unique-August-2019.pdf)  
Aston, J., Bennett, L., Murphy, H., **Odell, E.**, & Stevens, T. (2019). External evaluation of the Bridge to Work Programme. City Bridge Trust. [citybridgetrust.org.uk/wp-content/uploads/2019/07/Bridge-to-Work-Year-1-report.pdf](https://www.citybridgetrust.org.uk/wp-content/uploads/2019/07/Bridge-to-Work-Year-1-report.pdf)  
**Odell, E.** (2018). Disability, Rights and Vulnerability in British Parliamentary Debate. _SocArXiv_. DOI: [10.31235/osf.io/tqf5j](https://doi.org/10.31235/osf.io/tqf5j)  
Theobald, K., & **Odell, E.** (2015). Isolated schools: Out on a limb. Future Leaders Trust. [future-leaders.org.uk/documents/195/Isolated_schools_Out_on_a_limb.pdf](http://www.future-leaders.org.uk/documents/195/Isolated_schools_Out_on_a_limb.pdf)  







## R Packages  

**Odell, E.** (2020). `threesixtygiving`: Download Charitable Grants from the ‘360Giving’ Platform. [github.com/evanodell/threesixtygiving](https://github.com/evanodell/threesixtygiving)  
**Odell, E.** (2019). `guardianapi`: Access the ‘Guardian’ newspaper open data API. [github.com/evanodell/guardianapi](https://github.com/evanodell/guardianapi)  
**Odell, E.**, & Tierney, N. (2019). `ukpolice`: Download Data on UK Police and Crime. [github.com/evanodell/ukpolice](https://github.com/evanodell/ukpolice)  
**Odell, E.** (2019). `cqcr`: Access ‘Care Quality Commission’ Data. [github.com/evanodell/cqcr](https://github.com/evanodell/cqcr)  
**Odell, E.** (2018). `nomisr`: Access Nomis UK Labour Market Data. _Journal of Open Source Software_, 3(27), 859. DOI: [10.21105/joss.00859](https://doi.org/10.21105/joss.00859)  
**Odell, E.** (2018). `fixerapi`: An R Client for the ‘Fixer.io’ Currency API. [github.com/evanodell/fixerapi](https://github.com/evanodell/fixerapi)  
**Odell, E.** (2018). `refuge`: Locate Trans and Intersex-Friendly Toilets. [github.com/evanodell/refuge](https://github.com/evanodell/refuge)  
**Odell, E.** (2017). `hansard`: Accessing Westminster Parliament Data. [github.com/evanodell/hansard ](https://github.com/evanodell/hansard)  
**Odell, E.** (2017). `mnis`: Easy Downloading Capabilities for the Members’ Name Information Service. [github.com/evanodell/mnis](https://github.com/evanodell/mnis)  
**Odell, E.** (2017). `parlitools`: Tools for Analysing UK Politics. [github.com/evanodell/parlitools](https://github.com/evanodell/parlitools)  


## Datasets

**Odell, E.** (2019). Hansard Speeches V2.6.1 [dataset]. DOI: [10.5281/zenodo.780985](https://doi.org/10.5281/zenodo.780985)  
